"use client"
import React from "react"
import { Card } from "@/components/ui/Card"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { GitCommit, History, ArrowRight, RotateCcw } from "lucide-react"

export default function VersionsPage() {
  const versions = [
    { v: "V5", name: "Current State", time: "2026-08-23 21:05", agent: "Master Agent", changes: "Orchestrated final pipeline", rows: "150,000", active: true },
    { v: "V4", name: "Synthetic Data Added", time: "2026-08-23 21:04", agent: "Synthetic Data Agent", changes: "+25,000 SMOTE records added", rows: "150,000", active: false },
    { v: "V3", name: "Feature Engineering", time: "2026-08-23 21:03", agent: "Feature Agent", changes: "Added 17 features, removed 5", rows: "125,000", active: false },
    { v: "V2", name: "Data Cleaning", time: "2026-08-23 21:02", agent: "Quality Agent", changes: "Imputed missing, removed outliers", rows: "125,000", active: false },
    { v: "V1", name: "Original Upload", time: "2026-08-23 21:00", agent: "User", changes: "Initial dataset", rows: "125,000", active: false },
  ]

  return (
    <div className="space-y-6 pb-24 h-full flex flex-col">
      <div>
        <h1 className="text-2xl font-bold text-white mb-1">Dataset Version Control</h1>
        <p className="text-slate-400">Track and manage every transformation made by the AI workforce.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 flex-1">
        <Card className="lg:col-span-4 p-6 bg-black/40 backdrop-blur-xl border-white/5 flex flex-col h-full overflow-y-auto">
          <h3 className="text-sm font-bold text-slate-300 tracking-wider mb-6 flex items-center gap-2">
            <History size={16} className="text-brand-light" /> TIMELINE
          </h3>
          
          <div className="space-y-0 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-700 before:to-transparent">
            {versions.map((v, i) => (
              <div key={v.v} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active py-4">
                <div className={`flex items-center justify-center w-10 h-10 rounded-full border-4 border-[#09090b] ${v.active ? 'bg-brand-light shadow-[0_0_15px_rgba(45,212,191,0.5)]' : 'bg-slate-700'} shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 relative z-10`}>
                  <GitCommit size={16} className={v.active ? 'text-background' : 'text-slate-400'} />
                </div>
                <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-xl border border-white/5 bg-white/5 backdrop-blur-sm cursor-pointer hover:border-brand-light/30 transition-colors">
                  <div className="flex items-center justify-between mb-1">
                    <Badge className={v.active ? 'bg-brand-light/20 text-brand-light border-none' : 'bg-white/10 text-slate-300 border-none'}>{v.v}</Badge>
                    <span className="text-[10px] text-slate-500 font-mono">{v.time.split(' ')[1]}</span>
                  </div>
                  <h4 className={`font-bold text-sm ${v.active ? 'text-white' : 'text-slate-300'}`}>{v.name}</h4>
                  <div className="text-xs text-slate-500 mt-2">By: {v.agent}</div>
                </div>
              </div>
            ))}
          </div>
        </Card>

        <Card className="lg:col-span-8 p-6 bg-brand-dark/5 backdrop-blur-xl border-brand-light/20 flex flex-col relative overflow-hidden">
           <div className="absolute bottom-0 right-0 w-64 h-64 bg-brand-light/5 blur-[80px] rounded-full pointer-events-none" />
           <div className="flex items-center justify-between mb-8 relative z-10">
              <div>
                <Badge className="bg-brand-light/20 text-brand-light border-none mb-2">V4</Badge>
                <h2 className="text-2xl font-bold text-white">Synthetic Data Added</h2>
                <div className="text-sm text-slate-400 mt-1">Generated by Synthetic Data Agent at 21:04</div>
              </div>
              <div className="flex gap-3">
                <Button variant="outline" className="border-white/10 text-slate-300 hover:text-white hover:bg-white/5 gap-2">Compare</Button>
                <Button variant="outline" className="border-red-500/30 text-red-400 hover:bg-red-500/10 gap-2"><RotateCcw size={16}/> Restore Version</Button>
              </div>
           </div>

           <div className="grid grid-cols-2 gap-6 mb-8 relative z-10">
              <div className="bg-black/40 p-5 rounded-xl border border-white/5">
                 <div className="text-xs text-slate-500 uppercase tracking-widest mb-1">Rows Affected</div>
                 <div className="text-2xl font-bold text-white">125,000 <ArrowRight size={14} className="inline mx-2 text-slate-500"/> <span className="text-brand-light">150,000</span></div>
              </div>
              <div className="bg-black/40 p-5 rounded-xl border border-white/5">
                 <div className="text-xs text-slate-500 uppercase tracking-widest mb-1">Reason for change</div>
                 <div className="text-sm font-medium text-slate-300 mt-1">Target class imbalance detected (8%). Synthetic records generated to reach 42% distribution.</div>
              </div>
           </div>

           <div className="relative z-10 flex-1">
              <h4 className="text-sm font-bold text-slate-300 mb-4">CHANGELOG</h4>
              <ul className="space-y-3 text-sm text-slate-400 font-mono bg-black/40 p-4 rounded-xl border border-white/5">
                 <li className="flex gap-2"><span className="text-emerald-400">+</span> Added 25,000 rows (SMOTE)</li>
                 <li className="flex gap-2"><span className="text-blue-400">~</span> Target distribution updated</li>
                 <li className="flex gap-2"><span className="text-slate-500">*</span> Validated similarity: 94%</li>
              </ul>
           </div>
        </Card>
      </div>
    </div>
  )
}
